/* ===== e农通功能增强脚本：只新增功能，不改变原页面框架 ===== */
(function(){
  const LS={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch(e){return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  function toast(msg,type='success'){let w=$('.ent-toast-wrap');if(!w){w=document.createElement('div');w.className='ent-toast-wrap';document.body.appendChild(w)}const t=document.createElement('div');t.className='ent-toast '+type;t.textContent=msg;w.appendChild(t);setTimeout(()=>{t.style.opacity='0';t.style.transform='translateX(24px)';setTimeout(()=>t.remove(),250)},2200)}
  window.entToast=toast; const oldAlert=window.alert; window.alert=(m)=>toast(String(m||'操作成功'),'info');
  function current(){return location.pathname.split('/').pop()||'index.html'}
  document.addEventListener('DOMContentLoaded',()=>{initSearch();initBell();initCartFloat();initCourse();initMall();initMallDetail();initCommunity();initTags();initOnboarding();initMessages();initProfile();});

  function initSearch(){const bar=$('.search-bar'); if(!bar) return; const input=$('input',bar)||$('.search-input',bar); const btn=$('.search-btn',bar); if(!input) return; const data=[['培训课程','course.html'],['农机商城','mall.html'],['信息交流','community.html'],['个人中心','profile.html'],['拖拉机操作指南','course-detail.html'],['大疆植保无人机','mall-detail.html'],['消息中心','messages.html']];
    const panel=document.createElement('div');panel.className='ent-search-panel ent-hidden';bar.appendChild(panel);function render(){const q=input.value.trim();panel.innerHTML=''; if(!q){panel.classList.add('ent-hidden');return} const res=data.filter(x=>x[0].includes(q)).slice(0,6); if(!res.length) panel.innerHTML='<div class="ent-search-item">未找到结果，可换个关键词</div>'; res.forEach(([n,u])=>{const d=document.createElement('div');d.className='ent-search-item';d.textContent=n;d.onclick=()=>location.href=u;panel.appendChild(d)});panel.classList.remove('ent-hidden')} input.addEventListener('input',render); input.addEventListener('keydown',e=>{if(e.key==='Enter'){const first=$('.ent-search-item',panel); first?first.click():toast('暂无匹配结果','info')}}); btn&&btn.addEventListener('click',render); document.addEventListener('click',e=>{if(!bar.contains(e.target))panel.classList.add('ent-hidden')});}
  function initBell(){const bell=$('.fa-bell'); if(!bell) return; bell.parentElement.style.position='relative'; const unread=LS.get('ent_unread',3); if(unread>0){const b=document.createElement('span');b.className='ent-badge-dot';b.textContent=unread;bell.parentElement.appendChild(b)}}
  function productName(card){return ($('.product-title',card)||$('.g-title')||$('h1')||card).textContent.trim().replace(/\s+/g,' ')}
  function initCartFloat(){if(!/mall|profile/.test(current())) return; const f=document.createElement('div');f.className='ent-cart-float';f.innerHTML='<i class="fa-solid fa-cart-shopping"></i><span class="ent-badge-dot">0</span>';document.body.appendChild(f);f.onclick=showCart;updateCartBadge();}
  function updateCartBadge(){const n=LS.get('ent_cart',[]).reduce((a,b)=>a+(b.qty||1),0);$$('.ent-cart-float .ent-badge-dot').forEach(x=>x.textContent=n)}
  function addCart(item){const cart=LS.get('ent_cart',[]);const old=cart.find(x=>x.name===item.name); old?old.qty++:cart.push({...item,qty:1});LS.set('ent_cart',cart);updateCartBadge();toast('已加入购物车');}
  function showCart(){const cart=LS.get('ent_cart',[]);const mask=document.createElement('div');mask.className='ent-modal-mask';mask.innerHTML='<div class="ent-modal"><div class="ent-modal-head"><div class="ent-modal-title">我的购物车</div><div class="ent-modal-close">×</div></div><div class="ent-modal-body"></div></div>';const body=$('.ent-modal-body',mask); if(!cart.length) body.innerHTML='<div class="ent-empty">购物车还是空的，快去商城挑选农机设备吧。</div>'; else {cart.forEach((it,i)=>{const row=document.createElement('div');row.className='ent-cart-row';row.innerHTML=`<div><div class="ent-cart-name">${it.name}</div><div class="ent-cart-meta">数量：${it.qty}　价格：${it.price||'详询商家'}</div></div><button class="ent-mini-btn" data-i="${i}">删除</button><button class="ent-primary-btn">结算</button>`;body.appendChild(row)});body.insertAdjacentHTML('beforeend','<div style="text-align:right;margin-top:16px"><button class="ent-primary-btn ent-clear-cart">清空购物车</button></div>')} document.body.appendChild(mask);$('.ent-modal-close',mask).onclick=()=>mask.remove();mask.onclick=e=>{if(e.target===mask)mask.remove()}; $$('.ent-mini-btn',mask).forEach(b=>b.onclick=()=>{const c=LS.get('ent_cart',[]);c.splice(+b.dataset.i,1);LS.set('ent_cart',c);mask.remove();showCart();updateCartBadge()}); $('.ent-clear-cart',mask)?.addEventListener('click',()=>{LS.set('ent_cart',[]);mask.remove();updateCartBadge();toast('购物车已清空')});}
  function initMall(){if(current()!=='mall.html')return; $$('.btn-cart-sm').forEach(btn=>{btn.onclick=e=>{e.stopPropagation();const card=btn.closest('.product-card');addCart({name:productName(card),price:($('.price-current',card)||{}).textContent||''})}}); $$('.btn-buy-sm').forEach(btn=>{btn.onclick=e=>{e.stopPropagation();toast('已生成模拟订单，可在个人中心查看','info')}});}
  function initMallDetail(){if(current()!=='mall-detail.html')return; $('.btn-add-cart')?.addEventListener('click',e=>{e.preventDefault();addCart({name:productName(document),price:($('.price-main')||$('.g-price')||{}).textContent||'',qty:+($('#quantity')||{value:1}).value||1})}); $('.btn-buy-now')?.addEventListener('click',e=>{e.preventDefault();toast('已提交购买意向，商家将尽快联系您','info')});}
  function initCourse(){if(current()==='course.html'){$$('.course-card').forEach((c,i)=>{c.dataset.title=($('.course-title',c)||c).textContent.trim();});return} if(current()!=='course-detail.html')return; const key='ent_course_progress'; const p=LS.get(key,18); const bar=$('.progress-bar-current'); if(bar)bar.style.width=p+'%'; const tip=document.createElement('div');tip.className='ent-progress-tip';tip.textContent='学习进度已自动保存：'+p+'%';$('.video-container')?.appendChild(tip); $$('.lesson-item').forEach((it,idx)=>it.addEventListener('click',()=>{$$('.lesson-item').forEach(x=>x.classList.remove('active'));it.classList.add('active');const np=Math.min(100,Math.max(p,(idx+1)*8));LS.set(key,np);if(bar)bar.style.width=np+'%';tip.textContent='学习进度已自动保存：'+np+'%';toast('已切换课程小节')})); $('.play-btn-large')?.addEventListener('click',()=>{let np=Math.min(100,LS.get(key,18)+5);LS.set(key,np);if(bar)bar.style.width=np+'%';tip.textContent='学习进度已自动保存：'+np+'%';toast('开始学习，进度已更新')});}
  function initCommunity(){if(current()!=='community.html')return; const input=$('.publish-input'), btn=$('.publish-box .btn-primary'); btn&&btn.addEventListener('click',()=>{const txt=input.value.trim(); if(!txt)return toast('请输入动态内容','error'); const list=$('.feed-list'); const card=document.createElement('div');card.className='feed-card ent-highlight';card.innerHTML=`<div class="feed-user"><div class="user-info-left"><img src="images/avatar.png" class="user-avatar"><div class="user-meta"><div class="user-name">我</div><div class="post-time">刚刚发布</div></div></div></div><div class="feed-text">${txt}</div><div class="feed-actions"><span class="feed-action"><i class="fa-regular fa-thumbs-up"></i> 赞</span><span class="feed-action ent-comment-toggle"><i class="fa-regular fa-comment"></i> 评论</span><span class="feed-action"><i class="fa-regular fa-star"></i> 收藏</span></div>`;list.prepend(card);input.value='';toast('动态发布成功')}); $$('.feed-card').forEach(card=>{card.addEventListener('click',e=>{if(e.target.closest('.feed-action')){const a=e.target.closest('.feed-action');a.classList.toggle('ent-like-active');toast(a.classList.contains('ent-like-active')?'操作成功':'已取消','info')}})});}
  function initTags(){if(current()!=='tags.html')return; const saved=LS.get('ent_tags',[]); $$('.tag-item').forEach(t=>{const name=($('.tag-text',t)||t).textContent.trim(); if(saved.includes(name))t.classList.add('selected'); t.addEventListener('click',()=>setTimeout(()=>{const arr=$$('.tag-item.selected').map(x=>$('.tag-text',x).textContent.trim());LS.set('ent_tags',arr)},0))}); $('.btn-submit')?.addEventListener('click',e=>{LS.set('ent_tags',$$('.tag-item.selected').map(x=>$('.tag-text',x).textContent.trim()));toast('标签已保存')});}
  function initOnboarding(){if(current()!=='onboarding.html')return; $('#onboarding-form')?.addEventListener('submit',()=>{LS.set('ent_onboarding_done',true);toast('偏好信息已保存')});}
  function initMessages(){if(current()!=='messages.html')return; $$('.btn-read-all').forEach(b=>b.onclick=()=>{LS.set('ent_unread',0);$$('.ent-badge-dot').forEach(x=>x.remove());$$('.msg-item').forEach(x=>x.style.opacity=.6);toast('已全部标记为已读')});}
  function initProfile(){if(current()!=='profile.html')return; const box=$('#chatInput'); if(box){box.placeholder='请输入问题，例如：如何查看物流？';}}
})();

/* ===== e农通成熟网站功能增强：不改变原页面框架，只追加业务能力 ===== */
(function(){
  const LS={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch(e){return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const page=()=>location.pathname.split('/').pop()||'index.html';
  const toast=(m,t='info')=>window.entToast?window.entToast(m,t):alert(m);
  document.addEventListener('DOMContentLoaded',()=>{initMatureTools();initMember();initHomeOps();initCourseMature();initMallMature();initCommunityMature();initProfileMature();initShareAndReport();});

  function initMatureTools(){
    if(!document.body) return;
    if(LS.get('ent_dark',false)) document.body.classList.add('ent-dark');
    const wrap=document.createElement('div');wrap.className='ent-top-tools';wrap.innerHTML=`
      <button class="ent-tool-circle" title="智能客服" data-tool="kefu"><i class="fa-solid fa-headset"></i></button>
      <button class="ent-tool-circle" title="深色模式" data-tool="dark"><i class="fa-solid fa-moon"></i></button>
      <button class="ent-tool-circle" title="返回顶部" data-tool="top"><i class="fa-solid fa-arrow-up"></i></button>`;
    document.body.appendChild(wrap);
    const panel=document.createElement('div');panel.className='ent-kefu-panel';panel.innerHTML=`
      <div class="ent-kefu-head"><b><i class="fa-solid fa-robot"></i> e农通智能客服</b><span style="cursor:pointer" class="ent-kefu-close">×</span></div>
      <div class="ent-chip-row"><span class="ent-chip">物流怎么查？</span><span class="ent-chip">课程证书</span><span class="ent-chip">农机补贴</span><span class="ent-chip">售后维修</span></div>
      <div class="ent-kefu-body"><div class="ent-kefu-msg"><div class="ent-kefu-bubble">您好，我是小农助手。可以为您解答课程学习、农机选购、订单售后、政策补贴等问题。</div></div></div>
      <div class="ent-kefu-foot"><input placeholder="请输入问题..."><button class="ent-primary-btn">发送</button></div>`;
    document.body.appendChild(panel);
    wrap.addEventListener('click',e=>{const b=e.target.closest('button'); if(!b)return; const t=b.dataset.tool; if(t==='kefu') panel.style.display=panel.style.display==='block'?'none':'block'; if(t==='dark'){document.body.classList.toggle('ent-dark');LS.set('ent_dark',document.body.classList.contains('ent-dark'));toast('显示模式已切换')} if(t==='top') scrollTo({top:0,behavior:'smooth'});});
    $('.ent-kefu-close',panel).onclick=()=>panel.style.display='none';
    function ask(q){const body=$('.ent-kefu-body',panel); body.insertAdjacentHTML('beforeend',`<div class="ent-kefu-msg user"><div class="ent-kefu-bubble">${q}</div></div>`); const ans=answer(q); setTimeout(()=>{body.insertAdjacentHTML('beforeend',`<div class="ent-kefu-msg"><div class="ent-kefu-bubble">${ans}</div></div>`);body.scrollTop=body.scrollHeight},300); body.scrollTop=body.scrollHeight;}
    function answer(q){q=q||''; if(/物流|订单/.test(q))return '您可以在「个人中心」查看模拟订单与物流进度；商城加入购物车后会自动生成购买意向。'; if(/证书|课程/.test(q))return '课程学习进度达到 80% 后可生成学习证书，当前课程页已支持笔记保存与证书预览。'; if(/补贴|政策/.test(q))return '平台可按地区、农机类型展示政策补贴入口，后续可接入地方农机购置补贴目录。'; if(/售后|维修/.test(q))return '商品详情页可提交售后咨询，个人中心可查看服务工单进度。'; return '已收到，我建议您先查看首页智能推荐、商城对比与课程学习模块，也可以留下具体作物/设备型号以便精准推荐。';}
    $('.ent-kefu-foot button',panel).onclick=()=>{const inp=$('.ent-kefu-foot input',panel); if(!inp.value.trim())return; ask(inp.value.trim()); inp.value='';};
    $('.ent-kefu-foot input',panel).addEventListener('keydown',e=>{if(e.key==='Enter')$('.ent-kefu-foot button',panel).click();});
    $$('.ent-chip',panel).forEach(c=>c.onclick=()=>ask(c.textContent.trim()));
  }

  function initMember(){
    const user=LS.get('ent_user',null); const nav=$('.user-actions'); if(!nav)return;
    const btn=document.createElement('button'); btn.className='ent-mini-btn'; btn.style.marginRight='12px'; btn.innerHTML=user?`<i class="fa-solid fa-user-check"></i> ${user.name}`:'登录/注册'; nav.prepend(btn);
    btn.onclick=()=>showLogin();
    function showLogin(){const u=LS.get('ent_user',{name:'老张种粮',phone:'13800000000',role:'种植大户'}); const mask=document.createElement('div');mask.className='ent-modal-mask';mask.innerHTML=`<div class="ent-modal"><div class="ent-modal-head"><div class="ent-modal-title">会员登录 / 信息完善</div><div class="ent-modal-close">×</div></div><div class="ent-login-card"><input id="entName" placeholder="姓名/昵称" value="${u.name||''}"><input id="entPhone" placeholder="手机号" value="${u.phone||''}"><input id="entRole" placeholder="身份，例如：种植大户/农机经销商" value="${u.role||''}"><button class="ent-primary-btn">保存并登录</button></div></div>`;document.body.appendChild(mask);$('.ent-modal-close',mask).onclick=()=>mask.remove();$('.ent-primary-btn',mask).onclick=()=>{const nu={name:$('#entName',mask).value||'e农通用户',phone:$('#entPhone',mask).value,role:$('#entRole',mask).value};LS.set('ent_user',nu);toast('会员信息已保存');mask.remove();setTimeout(()=>location.reload(),400)};}
  }

  function initHomeOps(){if(page()!=='home.html')return; const main=$('.main-content')||document.body; const card=document.createElement('div');card.className='ent-smart-card';card.innerHTML=`<div class="ent-section-title"><i class="fa-solid fa-gauge-high"></i> 智慧农业运营看板</div><div class="ent-dashboard"><div class="ent-dash-card">今日访问<strong>12,486</strong></div><div class="ent-dash-card">课程学习<strong>3,218</strong></div><div class="ent-dash-card">农机询价<strong>869</strong></div><div class="ent-dash-card">问题解答<strong>1,526</strong></div></div><div class="ent-grid-3"><div class="ent-mini-panel"><h4>智能推荐</h4><p>根据您的标签，推荐「冬小麦病虫害防治」课程与植保无人机设备。</p></div><div class="ent-mini-panel"><h4>风险提醒</h4><p>未来三天部分地区存在降温和降雨风险，建议关注田间排水与苗情管理。</p></div><div class="ent-mini-panel"><h4>政策窗口</h4><p>农机购置补贴、合作社培训申报、数字农业项目可在本平台建立申报清单。</p></div></div>`; const target=$('.content-layout')||main.firstElementChild||main; target.parentNode.insertBefore(card,target);
  }

  function initCourseMature(){
    if(page()==='course.html'){$$('.course-card').forEach(c=>{if($('.ent-fav-btn',c))return; c.style.position='relative'; const fav=document.createElement('button');fav.className='ent-fav-btn';fav.innerHTML='<i class="fa-solid fa-star"></i>';fav.onclick=e=>{e.stopPropagation();fav.classList.toggle('active');saveList('ent_fav_courses',($('.course-title',c)||c).textContent.trim(),fav.classList.contains('active'));toast(fav.classList.contains('active')?'已收藏课程':'已取消收藏')}; c.appendChild(fav);}); return;}
    if(page()!=='course-detail.html')return; const box=document.createElement('div');box.className='ent-smart-card ent-notes-area';box.innerHTML=`<div class="ent-section-title"><i class="fa-solid fa-pen-to-square"></i> 学习笔记与证书</div><textarea class="ent-form-input" placeholder="记录本节课程重点、设备参数、田间操作注意事项..."></textarea><div style="display:flex;gap:10px;margin-top:10px;flex-wrap:wrap"><button class="ent-primary-btn ent-save-note">保存笔记</button><button class="ent-mini-btn ent-show-cert">生成学习证书</button></div>`;($('.course-content-section')||$('.main-content')).appendChild(box); const key='ent_course_note'; $('textarea',box).value=LS.get(key,''); $('.ent-save-note',box).onclick=()=>{LS.set(key,$('textarea',box).value);toast('学习笔记已保存')}; $('.ent-show-cert',box).onclick=()=>{const mask=document.createElement('div');mask.className='ent-modal-mask';mask.innerHTML=`<div class="ent-modal"><div class="ent-modal-head"><div class="ent-modal-title">学习证书预览</div><div class="ent-modal-close">×</div></div><div class="ent-cert"><i class="fa-solid fa-award" style="font-size:42px;color:#d6a629"></i><h2>e农通课程学习证书</h2><p>兹证明：${(LS.get('ent_user',{name:'老张种粮'}).name)} 已完成《新型大马力智能拖拉机操作指南》阶段学习。</p><p>证书编号：ENT-${Date.now().toString().slice(-8)}</p></div></div>`;document.body.appendChild(mask);$('.ent-modal-close',mask).onclick=()=>mask.remove();};
  }

  function initMallMature(){if(!/^mall/.test(page()))return; const compared=LS.get('ent_compare',[]); const bar=document.createElement('div');bar.className='ent-compare-bar';bar.innerHTML='<b>商品对比</b><div class="ent-compare-list"></div><button class="ent-primary-btn ent-do-compare">开始对比</button><button class="ent-mini-btn ent-clear-compare">清空</button>';document.body.appendChild(bar);function render(){const arr=LS.get('ent_compare',[]);$('.ent-compare-list',bar).innerHTML=arr.map(x=>`<span class="ent-compare-item">${x}</span>`).join('');bar.style.display=arr.length?'flex':'none'} render(); $('.ent-clear-compare',bar).onclick=()=>{LS.set('ent_compare',[]);render();toast('已清空对比')}; $('.ent-do-compare',bar).onclick=()=>showCompare(LS.get('ent_compare',[]));
    $$('.product-card').forEach(c=>{c.style.position='relative'; const title=($('.product-title',c)||c).textContent.trim(); if(!$('.ent-fav-btn',c)){const fav=document.createElement('button');fav.className='ent-fav-btn';fav.innerHTML='<i class="fa-solid fa-heart"></i>';fav.onclick=e=>{e.stopPropagation();fav.classList.toggle('active');saveList('ent_fav_products',title,fav.classList.contains('active'));toast(fav.classList.contains('active')?'已收藏商品':'已取消收藏')}; c.appendChild(fav);} if(!$('.ent-compare-btn',c)){const cp=document.createElement('button');cp.className='ent-compare-btn';cp.innerHTML='<i class="fa-solid fa-scale-balanced"></i>';cp.onclick=e=>{e.stopPropagation();let arr=LS.get('ent_compare',[]); if(!arr.includes(title))arr.push(title); if(arr.length>3)arr=arr.slice(-3);LS.set('ent_compare',arr);render();toast('已加入对比')}; c.appendChild(cp);} const info=document.createElement('div');info.className='ent-price-insight';info.textContent='支持补贴测算 / 分期询价 / 上门培训';($('.product-info',c)||c).appendChild(info);});
    if(page()==='mall-detail.html'){const panel=document.createElement('div');panel.className='ent-smart-card';panel.innerHTML=`<div class="ent-section-title"><i class="fa-solid fa-calculator"></i> 补贴与分期测算</div><div class="ent-grid-3"><div class="ent-mini-panel"><h4>预计补贴</h4><p>按地区和机型估算，可抵扣约 8% - 18%。</p></div><div class="ent-mini-panel"><h4>金融方案</h4><p>支持首付、分期、合作社集采报价。</p></div><div class="ent-mini-panel"><h4>售后保障</h4><p>上门安装、操作培训、年度保养提醒。</p></div></div>`;($('.product-detail-container')||$('.main-content')).appendChild(panel);}
  }
  function showCompare(arr){const mask=document.createElement('div');mask.className='ent-modal-mask';mask.innerHTML=`<div class="ent-modal"><div class="ent-modal-head"><div class="ent-modal-title">商品对比结果</div><div class="ent-modal-close">×</div></div><div class="ent-grid-3">${arr.map((n,i)=>`<div class="ent-mini-panel"><h4>${n}</h4><p>适用场景：${i===0?'大田作业':'精细化生产'}</p><p>服务：培训、质保、补贴咨询</p><p>建议：结合地块规模与预算选择。</p></div>`).join('')}</div></div>`;document.body.appendChild(mask);$('.ent-modal-close',mask).onclick=()=>mask.remove();}

  function initCommunityMature(){if(page()!=='community.html')return; $$('.btn-follow,.btn-follow-sm').forEach(b=>b.onclick=e=>{e.stopPropagation();const on=b.textContent.includes('已');b.textContent=on?'关注':'已关注';toast(on?'已取消关注':'关注成功')}); $$('.tool-btn').forEach(btn=>btn.onclick=()=>toast(btn.textContent.trim()+'功能已记录，可在发布动态中展示','info')); $$('.nav-menu-item').forEach(item=>item.onclick=()=>{$$('.nav-menu-item').forEach(x=>x.classList.remove('active'));item.classList.add('active');toast('已切换到：'+item.textContent.trim())});}

  function initProfileMature(){if(page()!=='profile.html')return; const container=$('.profile-container')||$('.main-content'); const orders=LS.get('ent_orders',[{name:'东方红 2004 履带式拖拉机',status:'运输中',step:3},{name:'植保无人机作业课程',status:'已开课',step:4}]); const card=document.createElement('div');card.className='ent-smart-card';card.innerHTML=`<div class="ent-section-title"><i class="fa-solid fa-clipboard-list"></i> 我的订单与服务工单</div><div class="ent-order-list">${orders.map(o=>`<div class="ent-order-card"><div><b>${o.name}</b><div style="color:#777;font-size:13px;margin-top:4px">状态：${o.status}</div><div class="ent-stepper">${[1,2,3,4].map(i=>`<span class="ent-step ${i<=o.step?'done':''}"></span>`).join('')}</div></div><button class="ent-mini-btn">查看详情</button></div>`).join('')}</div>`;container.appendChild(card); $$('.ent-order-card button',card).forEach(b=>b.onclick=()=>toast('订单详情：已完成下单、支付、出库、物流/服务跟进等流程展示','info'));
    const edit=document.createElement('button');edit.className='ent-mini-btn';edit.textContent='编辑资料';$('.hero-name-row')?.appendChild(edit);edit.onclick=()=>{const u=LS.get('ent_user',{name:'老张种粮',role:'认证种植大户'});const mask=document.createElement('div');mask.className='ent-modal-mask';mask.innerHTML=`<div class="ent-modal"><div class="ent-modal-head"><div class="ent-modal-title">编辑个人资料</div><div class="ent-modal-close">×</div></div><div class="ent-login-card"><input id="pname" value="${u.name||'老张种粮'}"><input id="prole" value="${u.role||'认证种植大户'}"><textarea id="pbio" class="ent-form-input">承包了500亩地，热爱尝试各种新型农机。</textarea><button class="ent-primary-btn">保存资料</button></div></div>`;document.body.appendChild(mask);$('.ent-modal-close',mask).onclick=()=>mask.remove();$('.ent-primary-btn',mask).onclick=()=>{LS.set('ent_user',{...u,name:$('#pname',mask).value,role:$('#prole',mask).value});$('.hero-name').textContent=$('#pname',mask).value;toast('资料已更新');mask.remove();};};
  }

  function initShareAndReport(){
    $$('[class*=share],.g-action-btn').forEach(el=>{if(/分享/.test(el.textContent))el.onclick=()=>{navigator.clipboard?.writeText(location.href);toast('链接已复制，可分享给微信/QQ好友')}});
    $$('[class*=report],.g-action-btn').forEach(el=>{if(/报错|侵权|举报/.test(el.textContent))el.onclick=()=>toast('已提交反馈，平台将在 1-3 个工作日内处理','info')});
  }
  function saveList(k,v,on){let arr=LS.get(k,[]); if(on&&!arr.includes(v))arr.push(v); if(!on)arr=arr.filter(x=>x!==v);LS.set(k,arr)}
})();

// 首页快捷服务跳转页交互增强
(function(){
  if(!/^service-/.test(location.pathname.split('/').pop())) return;
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  $$('.tab-btn').forEach(btn=>btn.addEventListener('click',()=>{
    $$('.tab-btn').forEach(b=>b.classList.remove('active'));
    btn.classList.add('active');
    const result=$('.service-result');
    if(result) result.textContent='已切换到「'+btn.textContent.trim()+'」分类，相关内容已为您筛选展示。';
  }));
  $$('.service-submit').forEach(btn=>btn.addEventListener('click',e=>{
    e.preventDefault();
    const result=$('.service-result');
    const msg=btn.getAttribute('data-msg')||'提交成功，平台将为您生成处理结果。';
    if(result) result.textContent=msg;
    const tip=document.createElement('div');
    tip.className='ent-toast';
    tip.textContent=msg;
    document.body.appendChild(tip);
    setTimeout(()=>tip.classList.add('show'),10);
    setTimeout(()=>{tip.classList.remove('show'); setTimeout(()=>tip.remove(),250)},2400);
  }));
})();
